import { WorkoutPlanForm } from "@/components/workout-plan-form";

export default function PersonalizedWorkoutPlanPage() {
  return (
    <div className="w-full py-16 md:py-24 bg-background">
      <div className="container mx-auto px-4 md:px-6">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h1 className="text-3xl md:text-4xl font-headline font-bold">Personalized Workout Plan Generation</h1>
          <p className="mt-4 text-muted-foreground">
            Fill out the form below to receive a customized workout plan tailored to your goals, experience, and resources, generated by our advanced AI.
          </p>
        </div>
        <WorkoutPlanForm />
      </div>
    </div>
  );
}
